org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.5
fabric_api_version=0.161.0+26.2
loom_version=1.17-SNAPSHOT

mod_id=autotpa
mod_name=AutoTPA
mod_version=1.0.0
mod_author=Fr4ncyILGrande
maven_group=de.fr4ncyilgrande
